#!/bin/bash 

pause() 
{ 
	SAVEDSTTY=`stty -g` 
	stty -echo 
	stty cbreak 
	dd if=/dev/tty bs=1 count=1 2> /dev/null 
	stty -raw 
	stty echo 
	stty $SAVEDSTTY 
}
echo "Press any key to continue!" 
pause
echo 